/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { CostOptimizationWhereUniqueInput } from "../../costOptimization/base/CostOptimizationWhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";

@InputType()
class CostOptimizationCreateNestedManyWithoutEc2InstancesInput {
  @Field(() => [CostOptimizationWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [CostOptimizationWhereUniqueInput],
  })
  connect?: Array<CostOptimizationWhereUniqueInput>;
}

export { CostOptimizationCreateNestedManyWithoutEc2InstancesInput as CostOptimizationCreateNestedManyWithoutEc2InstancesInput };
