/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Ec2InstanceCreateInput } from "./Ec2InstanceCreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateEc2InstanceArgs {
  @ApiProperty({
    required: true,
    type: () => Ec2InstanceCreateInput,
  })
  @ValidateNested()
  @Type(() => Ec2InstanceCreateInput)
  @Field(() => Ec2InstanceCreateInput, { nullable: false })
  data!: Ec2InstanceCreateInput;
}

export { CreateEc2InstanceArgs as CreateEc2InstanceArgs };
