/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Ec2InstanceWhereInput } from "./Ec2InstanceWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Ec2InstanceOrderByInput } from "./Ec2InstanceOrderByInput";

@ArgsType()
class Ec2InstanceFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Ec2InstanceWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Ec2InstanceWhereInput, { nullable: true })
  @Type(() => Ec2InstanceWhereInput)
  where?: Ec2InstanceWhereInput;

  @ApiProperty({
    required: false,
    type: [Ec2InstanceOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Ec2InstanceOrderByInput], { nullable: true })
  @Type(() => Ec2InstanceOrderByInput)
  orderBy?: Array<Ec2InstanceOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Ec2InstanceFindManyArgs as Ec2InstanceFindManyArgs };
