/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsDate } from "class-validator";
import { CostOptimizationUpdateManyWithoutEc2InstancesInput } from "./CostOptimizationUpdateManyWithoutEc2InstancesInput";
import { Type } from "class-transformer";
import { ScalingRecommendationUpdateManyWithoutEc2InstancesInput } from "./ScalingRecommendationUpdateManyWithoutEc2InstancesInput";
import { UtilizationMetricsUpdateManyWithoutEc2InstancesInput } from "./UtilizationMetricsUpdateManyWithoutEc2InstancesInput";

@InputType()
class Ec2InstanceUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  availabilityZone?: string | null;

  @ApiProperty({
    required: false,
    type: () => CostOptimizationUpdateManyWithoutEc2InstancesInput,
  })
  @ValidateNested()
  @Type(() => CostOptimizationUpdateManyWithoutEc2InstancesInput)
  @IsOptional()
  @Field(() => CostOptimizationUpdateManyWithoutEc2InstancesInput, {
    nullable: true,
  })
  costOptimizations?: CostOptimizationUpdateManyWithoutEc2InstancesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  instanceId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  instanceType?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  launchTime?: Date | null;

  @ApiProperty({
    required: false,
    type: () => ScalingRecommendationUpdateManyWithoutEc2InstancesInput,
  })
  @ValidateNested()
  @Type(() => ScalingRecommendationUpdateManyWithoutEc2InstancesInput)
  @IsOptional()
  @Field(() => ScalingRecommendationUpdateManyWithoutEc2InstancesInput, {
    nullable: true,
  })
  scalingRecommendations?: ScalingRecommendationUpdateManyWithoutEc2InstancesInput;

  @ApiProperty({
    required: false,
    type: () => UtilizationMetricsUpdateManyWithoutEc2InstancesInput,
  })
  @ValidateNested()
  @Type(() => UtilizationMetricsUpdateManyWithoutEc2InstancesInput)
  @IsOptional()
  @Field(() => UtilizationMetricsUpdateManyWithoutEc2InstancesInput, {
    nullable: true,
  })
  utilizationMetricsItems?: UtilizationMetricsUpdateManyWithoutEc2InstancesInput;
}

export { Ec2InstanceUpdateInput as Ec2InstanceUpdateInput };
