/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsDate } from "class-validator";
import { CostOptimizationCreateNestedManyWithoutEc2InstancesInput } from "./CostOptimizationCreateNestedManyWithoutEc2InstancesInput";
import { Type } from "class-transformer";
import { ScalingRecommendationCreateNestedManyWithoutEc2InstancesInput } from "./ScalingRecommendationCreateNestedManyWithoutEc2InstancesInput";
import { UtilizationMetricsCreateNestedManyWithoutEc2InstancesInput } from "./UtilizationMetricsCreateNestedManyWithoutEc2InstancesInput";

@InputType()
class Ec2InstanceCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  availabilityZone?: string | null;

  @ApiProperty({
    required: false,
    type: () => CostOptimizationCreateNestedManyWithoutEc2InstancesInput,
  })
  @ValidateNested()
  @Type(() => CostOptimizationCreateNestedManyWithoutEc2InstancesInput)
  @IsOptional()
  @Field(() => CostOptimizationCreateNestedManyWithoutEc2InstancesInput, {
    nullable: true,
  })
  costOptimizations?: CostOptimizationCreateNestedManyWithoutEc2InstancesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  instanceId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  instanceType?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  launchTime?: Date | null;

  @ApiProperty({
    required: false,
    type: () => ScalingRecommendationCreateNestedManyWithoutEc2InstancesInput,
  })
  @ValidateNested()
  @Type(() => ScalingRecommendationCreateNestedManyWithoutEc2InstancesInput)
  @IsOptional()
  @Field(() => ScalingRecommendationCreateNestedManyWithoutEc2InstancesInput, {
    nullable: true,
  })
  scalingRecommendations?: ScalingRecommendationCreateNestedManyWithoutEc2InstancesInput;

  @ApiProperty({
    required: false,
    type: () => UtilizationMetricsCreateNestedManyWithoutEc2InstancesInput,
  })
  @ValidateNested()
  @Type(() => UtilizationMetricsCreateNestedManyWithoutEc2InstancesInput)
  @IsOptional()
  @Field(() => UtilizationMetricsCreateNestedManyWithoutEc2InstancesInput, {
    nullable: true,
  })
  utilizationMetricsItems?: UtilizationMetricsCreateNestedManyWithoutEc2InstancesInput;
}

export { Ec2InstanceCreateInput as Ec2InstanceCreateInput };
