/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Ec2InstanceWhereUniqueInput } from "./Ec2InstanceWhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class Ec2InstanceFindUniqueArgs {
  @ApiProperty({
    required: true,
    type: () => Ec2InstanceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Ec2InstanceWhereUniqueInput)
  @Field(() => Ec2InstanceWhereUniqueInput, { nullable: false })
  where!: Ec2InstanceWhereUniqueInput;
}

export { Ec2InstanceFindUniqueArgs as Ec2InstanceFindUniqueArgs };
