/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Ec2InstanceWhereInput } from "./Ec2InstanceWhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Ec2InstanceCountArgs {
  @ApiProperty({
    required: false,
    type: () => Ec2InstanceWhereInput,
  })
  @Field(() => Ec2InstanceWhereInput, { nullable: true })
  @Type(() => Ec2InstanceWhereInput)
  where?: Ec2InstanceWhereInput;
}

export { Ec2InstanceCountArgs as Ec2InstanceCountArgs };
