/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { CostOptimizationListRelationFilter } from "../../costOptimization/base/CostOptimizationListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { ScalingRecommendationListRelationFilter } from "../../scalingRecommendation/base/ScalingRecommendationListRelationFilter";
import { UtilizationMetricsListRelationFilter } from "../../utilizationMetrics/base/UtilizationMetricsListRelationFilter";

@InputType()
class Ec2InstanceWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  availabilityZone?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CostOptimizationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CostOptimizationListRelationFilter)
  @IsOptional()
  @Field(() => CostOptimizationListRelationFilter, {
    nullable: true,
  })
  costOptimizations?: CostOptimizationListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  instanceId?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  instanceType?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  launchTime?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ScalingRecommendationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScalingRecommendationListRelationFilter)
  @IsOptional()
  @Field(() => ScalingRecommendationListRelationFilter, {
    nullable: true,
  })
  scalingRecommendations?: ScalingRecommendationListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UtilizationMetricsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UtilizationMetricsListRelationFilter)
  @IsOptional()
  @Field(() => UtilizationMetricsListRelationFilter, {
    nullable: true,
  })
  utilizationMetricsItems?: UtilizationMetricsListRelationFilter;
}

export { Ec2InstanceWhereInput as Ec2InstanceWhereInput };
