/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ScalingRecommendationWhereUniqueInput } from "../../scalingRecommendation/base/ScalingRecommendationWhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";

@InputType()
class ScalingRecommendationUpdateManyWithoutEc2InstancesInput {
  @Field(() => [ScalingRecommendationWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [ScalingRecommendationWhereUniqueInput],
  })
  connect?: Array<ScalingRecommendationWhereUniqueInput>;

  @Field(() => [ScalingRecommendationWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [ScalingRecommendationWhereUniqueInput],
  })
  disconnect?: Array<ScalingRecommendationWhereUniqueInput>;

  @Field(() => [ScalingRecommendationWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [ScalingRecommendationWhereUniqueInput],
  })
  set?: Array<ScalingRecommendationWhereUniqueInput>;
}

export { ScalingRecommendationUpdateManyWithoutEc2InstancesInput as ScalingRecommendationUpdateManyWithoutEc2InstancesInput };
