/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Ec2InstanceWhereUniqueInput } from "./Ec2InstanceWhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Ec2InstanceUpdateInput } from "./Ec2InstanceUpdateInput";

@ArgsType()
class UpdateEc2InstanceArgs {
  @ApiProperty({
    required: true,
    type: () => Ec2InstanceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Ec2InstanceWhereUniqueInput)
  @Field(() => Ec2InstanceWhereUniqueInput, { nullable: false })
  where!: Ec2InstanceWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Ec2InstanceUpdateInput,
  })
  @ValidateNested()
  @Type(() => Ec2InstanceUpdateInput)
  @Field(() => Ec2InstanceUpdateInput, { nullable: false })
  data!: Ec2InstanceUpdateInput;
}

export { UpdateEc2InstanceArgs as UpdateEc2InstanceArgs };
