/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { UtilizationMetricsWhereUniqueInput } from "../../utilizationMetrics/base/UtilizationMetricsWhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";

@InputType()
class UtilizationMetricsCreateNestedManyWithoutEc2InstancesInput {
  @Field(() => [UtilizationMetricsWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [UtilizationMetricsWhereUniqueInput],
  })
  connect?: Array<UtilizationMetricsWhereUniqueInput>;
}

export { UtilizationMetricsCreateNestedManyWithoutEc2InstancesInput as UtilizationMetricsCreateNestedManyWithoutEc2InstancesInput };
