/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { UtilizationMetricsWhereUniqueInput } from "../../utilizationMetrics/base/UtilizationMetricsWhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";

@InputType()
class UtilizationMetricsUpdateManyWithoutEc2InstancesInput {
  @Field(() => [UtilizationMetricsWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [UtilizationMetricsWhereUniqueInput],
  })
  connect?: Array<UtilizationMetricsWhereUniqueInput>;

  @Field(() => [UtilizationMetricsWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [UtilizationMetricsWhereUniqueInput],
  })
  disconnect?: Array<UtilizationMetricsWhereUniqueInput>;

  @Field(() => [UtilizationMetricsWhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [UtilizationMetricsWhereUniqueInput],
  })
  set?: Array<UtilizationMetricsWhereUniqueInput>;
}

export { UtilizationMetricsUpdateManyWithoutEc2InstancesInput as UtilizationMetricsUpdateManyWithoutEc2InstancesInput };
